// examples/templates/vue/frontend/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

const count = ref(0);

onMounted(async () => {
  count.value = Number(await window.getInitialCount());
});

async function increment() {
  count.value = Number(await window.increment());
}

async function decrement() {
  count.value = Number(await window.decrement());
}
</script>

<template>
  <main class="counter">
    <h1>Ring + Vue</h1>
    <p class="count">{{ count }}</p>
    <div class="buttons">
      <button @click="decrement">- Decrement</button>
      <button @click="increment">+ Increment</button>
    </div>
  </main>
</template>

// examples/templates/react/frontend/src/App.tsx
import { useEffect, useState } from "react";

export default function App() {
  const [count, setCount] = useState(0);

  useEffect(() => {
    window.getInitialCount().then((n) => setCount(Number(n)));
  }, []);

  const increment = async () => setCount(Number(await window.increment()));
  const decrement = async () => setCount(Number(await window.decrement()));

  return (
    <main className="counter">
      <h1>Ring + React</h1>
      <p className="count">{count}</p>
      <div className="buttons">
        <button onClick={decrement}>- Decrement</button>
        <button onClick={increment}>+ Increment</button>
      </div>
    </main>
  );
}
