// examples/templates/svelte/frontend/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";

  let count = $state(0);

  onMount(async () => {
    count = Number(await window.getInitialCount());
  });

  async function increment() {
    count = Number(await window.increment());
  }

  async function decrement() {
    count = Number(await window.decrement());
  }
</script>

<main class="counter">
  <h1>Ring + Svelte</h1>
  <p class="count">{count}</p>
  <div class="buttons">
    <button onclick={decrement}>- Decrement</button>
    <button onclick={increment}>+ Increment</button>
  </div>
</main>

// examples/templates/vue/frontend/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

const count = ref(0);

onMounted(async () => {
  count.value = Number(await window.getInitialCount());
});

async function increment() {
  count.value = Number(await window.increment());
}

async function decrement() {
  count.value = Number(await window.decrement());
}
</script>

<template>
  <main class="counter">
    <h1>Ring + Vue</h1>
    <p class="count">{{ count }}</p>
    <div class="buttons">
      <button @click="decrement">- Decrement</button>
      <button @click="increment">+ Increment</button>
    </div>
  </main>
</template>
